# Bibliotecas

In [1]:
import pandas as pd #análise de dados em tabelas
import numpy as np #análise de números
import seaborn as sb #análise em gráficos

# Stroke Machine Learning Classification Model
With categorical data 
and train and test sets

In [2]:
train = 'http://bit.ly/avctreino'
test = 'http://bit.ly/avcteste'

In [3]:
train = pd.read_csv(train, decimal='.')
test = pd.read_csv(test, decimal='.')

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30380 entries, 0 to 30379
Data columns (total 12 columns):
id                   30380 non-null int64
gender               30380 non-null int64
age                  30380 non-null int64
hypertension         30380 non-null int64
heart_disease        30380 non-null int64
ever_married         30380 non-null int64
work_type            30380 non-null int64
residence_type       30380 non-null int64
avg_glucose_level    30380 non-null int64
bmi                  30380 non-null int64
smoking_status       30380 non-null int64
stroke               30380 non-null int64
dtypes: int64(12)
memory usage: 2.8 MB


In [5]:
train.columns.tolist()

['id',
 'gender',
 'age',
 'hypertension',
 'heart_disease',
 'ever_married',
 'work_type',
 'residence_type',
 'avg_glucose_level',
 'bmi',
 'smoking_status',
 'stroke']

In [6]:
X_train = train[['gender',
 'age',
 'hypertension',
 'heart_disease',
 'ever_married',
 'work_type',
 'residence_type',
 'avg_glucose_level',
 'bmi',
 'smoking_status']]
y_train = train['stroke']

In [8]:
y_train.head()

0    0
1    0
2    0
3    0
4    0
Name: stroke, dtype: int64

In [9]:
X_test = test[['gender',
 'age',
 'hypertension',
 'heart_disease',
 'ever_married',
 'work_type',
 'residence_type',
 'avg_glucose_level',
 'bmi',
 'smoking_status']]
y_test = test['stroke']

In [11]:
X = pd.concat([X_train, X_test])
y = pd.concat([y_train, y_test])

### Dictionary
- Gender: Male= 0, Female= 1
- Age: Young= 0, Older= 1 (> 35)
- Hypertension: No= 0, Yes= 1
- Heart Disease: No= 0, Yes= 1
- Ever Married: No= 0, Yes= 1
- Works: 0 = No, 1 = Yes
- Residence type: Rural= 0, Urban= 1
- Glucose Level: 0= Low, 1= High (140mg, after meal)
- BMI (body mass index): 0= Low, 1= High (30)
- Smoking Status: 0 = never smoked, 1 = smoked

## Explore Data

In [18]:
df = X.join(y, how='outer')
df.head()

gender  age  hypertension  heart_disease  ever_married  work_type  \
0       1    0             0              0             0          1   
0       1    0             0              0             0          1   
0       1    1             0              0             0          1   
0       1    1             0              0             0          1   
1       1    1             1              0             0          1   

   residence_type  avg_glucose_level  bmi  smoking_status  stroke  
0               0                  0    0               0       0  
0               0                  0    0               0       0  
0               0                  0    0               0       0  
0               0                  0    0               0       0  
1               1                  0    1               0       0

## Prepare model

In [25]:
!pip install scikit-plot

In [27]:
# Import models
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB

clf1 = LogisticRegression() # regressão logistica
clf2 = RandomForestClassifier() # arvores aleatorias
clf3 = xgb.XGBClassifier() # boost gradient
clf4 = SVC(gamma='auto')
clf5 = KNeighborsClassifier(n_neighbors=3)
clf6 = LinearDiscriminantAnalysis()
clf7 = GaussianNB()

# Train, Predict and Evaluate the model 
from sklearn.metrics import accuracy_score, classification_report, recall_score, confusion_matrix
from sklearn.model_selection import cross_val_score
for clf, label in zip([clf1, clf2, clf3, clf4, clf5, clf6, clf7], 
                      ['Logistic Regression', 'Random Forest', 'XGBoost', 
                       'SVM', 'KNN', 'LDA', 'GausianNB']):
    clf.fit(X_train, y_train) #training model
    p = clf.predict(X_test) #predicting model
    cv_score = cross_val_score(clf, X, y, cv=10, scoring='roc_auc')
    score = clf.score(X_test, y_test)
    print(label)
    print('\n')
    print('Sensibilidade =', recall_score(y_test, p))
    print('\n')
    print("=== Confusion Matrix ===")
    print(confusion_matrix(y_test, p))
    print('\n')
    print("=== Classification Report ===")
    print(classification_report(y_test, p))
    print('\n')
    print("=== All AUC Scores ===")
    print(cv_score)
    print('\n')
    print("=== Mean AUC Score ===")
    print("Mean AUC Score: ", label, cv_score.mean())
    print("_______________________________________________________")


C:\Users\fabia\Miniconda3\envs\ds\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\fabia\Miniconda3\envs\ds\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\fabia\Miniconda3\envs\ds\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\fabia\Miniconda3\envs\ds\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\fabia\Miniconda3\envs\ds\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to '

Logistic Regression


Sensibilidade = 0.0


=== Confusion Matrix ===
[[12785     0]
 [  235     0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     12785
           1       0.00      0.00      0.00       235

    accuracy                           0.98     13020
   macro avg       0.49      0.50      0.50     13020
weighted avg       0.96      0.98      0.97     13020



=== All AUC Scores ===
[0.79700206 0.81048298 0.77877504 0.77422421 0.78962868 0.79225024
 0.74702349 0.73108064 0.77514006 0.79276112]


=== Mean AUC Score ===
Mean AUC Score:  Logistic Regression 0.7788368528305278
_______________________________________________________
Random Forest


Sensibilidade = 0.0


=== Confusion Matrix ===
[[12782     3]
 [  235     0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     12785
           1       0.00      0.

C:\Users\fabia\Miniconda3\envs\ds\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


SVM


Sensibilidade = 0.0


=== Confusion Matrix ===
[[12785     0]
 [  235     0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     12785
           1       0.00      0.00      0.00       235

    accuracy                           0.98     13020
   macro avg       0.49      0.50      0.50     13020
weighted avg       0.96      0.98      0.97     13020



=== All AUC Scores ===
[0.51111679 0.57337733 0.56851244 0.56502906 0.46639654 0.52348272
 0.59162816 0.63205188 0.58710487 0.63973336]


=== Mean AUC Score ===
Mean AUC Score:  SVM 0.5658433140528468
_______________________________________________________


C:\Users\fabia\Miniconda3\envs\ds\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


KNN


Sensibilidade = 0.00851063829787234


=== Confusion Matrix ===
[[12693    92]
 [  233     2]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.98      0.99      0.99     12785
           1       0.02      0.01      0.01       235

    accuracy                           0.98     13020
   macro avg       0.50      0.50      0.50     13020
weighted avg       0.96      0.98      0.97     13020



=== All AUC Scores ===
[0.54479088 0.5352482  0.50468669 0.53749744 0.53200014 0.55602281
 0.49924497 0.53070334 0.52498511 0.53918215]


=== Mean AUC Score ===
Mean AUC Score:  KNN 0.5304361737718847
_______________________________________________________
LDA


Sensibilidade = 0.04680851063829787


=== Confusion Matrix ===
[[12716    69]
 [  224    11]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.98      0.99      0.99     12785
           1       0.14      0.05      0.

In [28]:
print('Melhor modelo = Gaussian NB')

Melhor modelo = Gaussian NB
